# Generated by Django 3.2.9 on 2022-01-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_phone', models.CharField(max_length=22)),
                ('admin_email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('inst_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('inst_name', models.CharField(max_length=100)),
                ('inst_designation', models.CharField(max_length=150)),
                ('inst_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=22)),
                ('user_email', models.CharField(max_length=255)),
            ],
        ),
    ]
