# Generated by Django 3.2.9 on 2022-01-12 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=200)),
                ('course_desc', models.CharField(max_length=255)),
                ('course_fee', models.IntegerField()),
                ('cat_id', models.ForeignKey(db_column='cat_id', on_delete=django.db.models.deletion.CASCADE, to='backend.category')),
            ],
        ),
    ]
