# Generated by Django 3.2.9 on 2022-01-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_course_course_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('img_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('img_desc', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
            ],
        ),
    ]
