# Generated by Django 3.2.9 on 2022-01-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='img_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='inst_description',
            field=models.TextField(),
        ),
    ]
