# Generated by Django 3.2.9 on 2022-01-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20220113_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=255)),
                ('blog', models.TextField()),
                ('blog_author', models.CharField(max_length=100)),
                ('blog_img', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('publish_date', models.DateField()),
            ],
        ),
    ]
