# Generated by Django 3.2.9 on 2022-01-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_designation', models.CharField(max_length=150)),
                ('review', models.TextField()),
                ('reviewer_img', models.ImageField(blank=True, null=True, upload_to='reviewer_images/')),
            ],
        ),
    ]
