# Generated by Django 3.2.9 on 2022-01-15 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='inst_id',
            field=models.ForeignKey(db_column='inst_id', default=13, on_delete=django.db.models.deletion.CASCADE, to='backend.instructor'),
            preserve_default=False,
        ),
    ]
